import { Injectable, signal } from '@angular/core';

export type Language = 'th' | 'en' | 'zh' | 'ja' | 'ko';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  currentLang = signal<Language>('th');

  private translations: Record<Language, Record<string, string>> = {
    th: {
      dashboard: 'แดชบอร์ด',
      home: 'หน้าแรก',
      overview: 'ภาพรวม',
      salary_record: 'บันทึกเงินเดือน',
      employment_contract: 'สัญญาจ้าง',
      companies: 'บริษัท',
      tax_settings: 'ตั้งค่าภาษี',
      profile: 'โปรไฟล์',
      admin_panel: 'แผงควบคุมผู้ดูแล',
      user_management: 'จัดการผู้ใช้งาน',
      logout: 'ออกจากระบบ',
      logged_in_as: 'เข้าสู่ระบบในชื่อ:',
      search_placeholder: 'ค้นหา...',
      notice_title: 'ประกาศ',
      notice_content: 'เว็บนี้ทำขึ้นเพื่อ ใช้งานส่วนตัวในชีวิตประจำวันเพียงเท่านั้น และสามารถใช้ตรวจเช็คยอดรายได้ตัวบุคคล',
      close: 'ปิด',
      language: 'ภาษา',
      font_size: 'ขนาดตัวอักษร',
      font_small: 'เล็ก',
      font_medium: 'ปกติ',
      font_large: 'ใหญ่',
      monthly_summary_title: 'สรุปภาพรวมรายได้รายเดือน',
      month: 'เดือน',
      contract_salary: 'เงินเดือนตามสัญญา',
      gross_income: 'ได้รับจริง (Gross)',
      pending_amount: 'ยอดค้างจ่าย',
      net_income: 'รายได้สุทธิ (Net)',
      pending_payment: 'รอรับเงิน',
      complete_payment: 'ครบถ้วน',
      no_data: 'ไม่พบข้อมูลสรุปรายได้',
      net_after_deductions: 'เงินเดือนหลังหักสปส.และภาษี',
      total_summary: 'รวมทั้งหมด',
      salary_management_title: 'จัดการข้อมูลเงินเดือน',
      monthly_records_for: 'รายการบันทึกประจำเดือน',
      items: 'รายการ',
      income_type: 'ประเภท',
      due_paid_date: 'วันกำหนดจ่าย/วันที่จ่าย',
      status_interest: 'สถานะ/ดอกเบี้ย',
      check_interest: 'ตรวจสอบดอกเบี้ย',
      edit: 'แก้ไข',
      delete: 'ลบ',
      no_records_this_month: 'ไม่มีรายการบันทึกในเดือนนี้',
      interest_details: 'รายละเอียดดอกเบี้ย',
      labor_law_calc: 'คำนวณตามกฎหมายแรงงาน (15% ต่อปี)',
      principal_amount: 'เงินต้นที่ค้าง',
      late_days: 'จำนวนวันล่าช้า',
      days: 'วัน',
      interest_15: 'ดอกเบี้ย 15%',
      penalty_money: 'เงินเพิ่ม (Penalty)',
      total_additional_received: 'รวมยอดที่ต้องได้รับเพิ่ม',
      download_report: 'ดาวน์โหลดรายงาน',
      close_window: 'ปิดหน้าต่าง'
    },
    en: {
      dashboard: 'Dashboard',
      home: 'Home',
      overview: 'Overview',
      salary_record: 'Salary Record',
      employment_contract: 'Employment Contract',
      companies: 'Companies',
      tax_settings: 'Tax Settings',
      profile: 'Profile',
      admin_panel: 'Admin Panel',
      user_management: 'User Management',
      logout: 'Logout',
      logged_in_as: 'Logged in as:',
      search_placeholder: 'Search for...',
      notice_title: 'Notice',
      notice_content: 'This website is made for personal daily use only and can be used to check individual income.',
      close: 'Close',
      language: 'Language',
      font_size: 'Font Size',
      font_small: 'Small',
      font_medium: 'Normal',
      font_large: 'Large',
      monthly_summary_title: 'Monthly Income Overview',
      month: 'Month',
      contract_salary: 'Contract Salary',
      gross_income: 'Actual Received (Gross)',
      pending_amount: 'Pending Amount',
      net_income: 'Net Income',
      pending_payment: 'Pending',
      complete_payment: 'Complete',
      no_data: 'No summary data found',
      net_after_deductions: 'Salary after SS/Tax',
      total_summary: 'Grand Total',
      salary_management_title: 'Salary Management',
      monthly_records_for: 'Monthly Records for',
      items: 'items',
      income_type: 'Type',
      due_paid_date: 'Due/Paid Date',
      status_interest: 'Status/Interest',
      check_interest: 'Check Interest',
      edit: 'Edit',
      delete: 'Delete',
      no_records_this_month: 'No records this month',
      interest_details: 'Interest Details',
      labor_law_calc: 'Calculated by labor law (15% per year)',
      principal_amount: 'Principal Amount',
      late_days: 'Late Days',
      days: 'days',
      interest_15: 'Interest 15%',
      penalty_money: 'Penalty Money',
      total_additional_received: 'Total Additional Received',
      download_report: 'Download Report',
      close_window: 'Close Window'
    },
    zh: {
      dashboard: '仪表板',
      home: '首页',
      overview: '概览',
      salary_record: '工资记录',
      employment_contract: '雇用合同',
      companies: '公司',
      tax_settings: '税务设置',
      profile: '个人资料',
      admin_panel: '管理面板',
      user_management: '用户管理',
      logout: '退出登录',
      logged_in_as: '登录身份:',
      search_placeholder: '搜索...',
      notice_title: '通知',
      notice_content: '本网站仅供个人日常ใช้，可用于查询个人收入。',
      close: '关闭',
      language: '语言',
      font_size: '字体大小',
      font_small: '小',
      font_medium: '正常',
      font_large: '大',
      monthly_summary_title: '月度收入概况',
      month: '月份',
      contract_salary: '合同工资',
      gross_income: '实际收入 (税前)',
      pending_amount: '待付金额',
      net_income: '净收入',
      pending_payment: '待处理',
      complete_payment: '已完成',
      no_data: '未发现摘要数据',
      net_after_deductions: '扣除社保/税后工资',
      total_summary: '总计',
      download_report: '下载报告'
    },
    ja: {
      dashboard: 'ダッシュボード',
      home: 'ホーム',
      overview: '概要',
      salary_record: '給与記録',
      employment_contract: '雇用契約',
      companies: '会社',
      tax_settings: '税務設定',
      profile: 'プロフィール',
      admin_panel: '管理パネル',
      user_management: 'ユーザー管理',
      logout: 'ログアウト',
      logged_in_as: 'ログイン中:',
      search_placeholder: '検索...',
      notice_title: '通知',
      notice_content: 'このウェブサイトは個人の日常使用のみを目的として作成されており、個人の収入を確認するために使用できます。',
      close: '閉じる',
      language: '言語',
      font_size: '文字サイズ',
      font_small: '小',
      font_medium: '通常',
      font_large: '大',
      monthly_summary_title: '月間収支概要',
      month: '月',
      contract_salary: '契約給ย',
      gross_income: '実績額 (総額)',
      pending_amount: '未払金額',
      net_income: '手取り額 (純額)',
      pending_payment: '保留中',
      complete_payment: '完了',
      no_data: 'サマリーデータが見つかりません',
      net_after_deductions: '社保・税引後給ย',
      total_summary: '合計',
      download_report: 'レポートをダウンロード'
    },
    ko: {
      dashboard: '대시보드',
      home: '홈',
      overview: '개요',
      salary_record: '급여 기록',
      employment_contract: '고용 계약',
      companies: '회사',
      tax_settings: '세무 설정',
      profile: '프로필',
      admin_panel: '관리 패널',
      user_management: '사용자 관리',
      report_management: '보고서 관리',
      logout: '로그아웃',
      logged_in_as: '로그인 계정:',
      search_placeholder: '검색...',
      notice_title: '공지사항',
      notice_content: '본 웹사이트는 개인적인 일상 용도로만 제작되었으며 개인 소득 확인용으로 사용할 수 있습니다.',
      close: '닫기',
      language: '언어',
      font_size: '글자 크기',
      font_small: '작게',
      font_medium: '보통',
      font_large: '크게',
      monthly_summary_title: '월간 소득 요약',
      month: '월',
      contract_salary: '계약 급여',
      gross_income: '실제 수령액 (총액)',
      pending_amount: '미지급 금액',
      net_income: '순소득 (실수령)',
      pending_payment: '지급 대기',
      complete_payment: '지급 완료',
      no_data: '요약 데이터가 없습니다',
      net_after_deductions: '사회보험 및 세금 공제 후 급여',
      total_summary: '합계',
      salary_management_title: '급여 관리',
      monthly_records_for: '월간 기록',
      items: '건',
      income_type: '유형',
      due_paid_date: '지급 기한/지급일',
      status_interest: '상태/이자',
      check_interest: '이자 확인',
      edit: '수정',
      delete: '삭제',
      no_records_this_month: '이번 달 기록이 없습니다',
      interest_details: '이자 상세',
      labor_law_calc: '노동법 기준 계산 (연 15%)',
      principal_amount: '미지급 원금',
      late_days: '지연 일수',
      days: '일',
      interest_15: '이자 15%',
      penalty_money: '가산금 (Penalty)',
      total_additional_received: '총 추가 수령액',
      download_report: '보고서 다운로드',
      close_window: '창 닫기'
    }
  };

  translate(key: string): string {
    return this.translations[this.currentLang()][key] || key;
  }

  setLanguage(lang: Language) {
    this.currentLang.set(lang);
  }
}

